apiVersion: v1
kind: ConfigMap
metadata:
  name: synergychat-crawler-configmap
data:
  CRAWLER_PORT: "8080"
  CRAWLER_DB_PATH: /cache/db
  CRAWLER_KEYWORDS: love,hate,joy,sadness,anger,disgust,fear,surprise
